### ISSUE TITLE
Specific example of polyfill import?

### ISSUE THREAD

**Issue by distante** [JRJurman/rollup-plugin-polyfill#3]
Hi! 

I want to use this plugin but I am not sure how to... I want to import [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill) into my `index.js` but no idea how to do it. I installed the desired polyfill into `node_modules` and this is my rollup config.

```
import polyfill from 'rollup-plugin-polyfill';
import typescript from 'rollup-plugin-typescript';

export default {
  input: './src/index.ts',
  output: {
    banner: `/**
    file: './dist-bundles/iife/index.js',
    format: 'iife',
    name: 'logger'
  },
  plugins: [
    typescript({
      sourceMap: false,
      target: 'es3'
    }),
    polyfill('index.js', ['proxy-polyfill'])
  ],
};
```

I have tried with : 
`polyfill('index.js', ['proxy-polyfill'])`
` polyfill('index.js', ['./node_modules/proxy-polyfill'])`
` polyfill('./dist-bundles/iife/index.js', ['./node_modules/proxy-polyfill'])`
` polyfill('./dist-bundles/iife/index.js', ['proxy-polyfill'])`
` polyfill('./src/index.ts', ['proxy-polyfill'])`

and nothing worked. I am lost... Could you guide me?

**Comment by JRJurman** [comment]
@distante sorry, just saw this today, I'll take a look and see if I can reproduce. Do you have an example project I can look at?

**Comment by distante** [comment]
Hi @JRJurman, I tried to use it in [this repo](https://github.com/distante/Saninn-logger) but I was unsuccessful. I Finally used an raw npm script to concatenate the polyfills because I didn't hat any other idea.

**Comment by JRJurman** [comment]
@distante While I was able to get it working right away for my `rollup-plugin-polyfill/example` I was noticing the following warning when trying to add it to your project (note: I was fooling around with different input files, so ignore the specific `src/index.ts`):
```
(!) Unresolved dependencies
https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency
proxy-polyfill (imported by src/index.ts)
```

From the docs in that link, it appears you need `rollup-plugin-node-resolve`
The resulting config that I was able to come up with looked like this:
```javascript
import polyfill from 'rollup-plugin-polyfill';
import resolve from 'rollup-plugin-node-resolve';
import typescript from 'rollup-plugin-typescript';

export default {
  input: './src/@saninn__logger.ts',
  output: {
    banner: `/**
 *  @license
 *
 *  Copyright Saninn Salas Diaz All Rights Reserved.
 *
 *  Released under the MIT License
 *
 *  http://www.saninnsalas.com
 */`,
    file: './dist-bundles/iife/@saninn__logger.js',
    format: 'iife',
    name: 'SaninnLogger'
  },
  plugins: [
    polyfill('./src/@saninn__logger.ts', ['proxy-polyfill']),
    resolve(),
    typescript({
      // lib: ["es5", "es6", "dom"],
      sourceMap: false,
      target: 'es3'
    })
  ]
};
```

And resulted in the following appearing at the top of the build
```javascript
// ...
(function(scope) {
    if (scope['Proxy']) {
      return;
    }
    scope.Proxy = require('./proxy.js')();
    scope.Proxy['revocable'] = scope.Proxy.revocable;
  })(
    ('undefined' !== typeof process &&
      '[object process]' === {}.toString.call(process)) ||
    ('undefined' !== typeof navigator && navigator.product === 'ReactNative')
      ? global
      : self
  );

  var LoggerTypesEnum;
  (function (LoggerTypesEnum) {
      LoggerTypesEnum["log"] = "log";
      LoggerTypesEnum["dir"] = "dir";
      LoggerTypesEnum["warn"] = "warn";
      LoggerTypesEnum["error"] = "error";
  })(LoggerTypesEnum || (LoggerTypesEnum = {}));

  var SaninnLogger = (function () {
// ...
```

Does that look like it solves your use case? I'm not 100% familiar with all the different types of builds, and I'm guessing this is an artifact of building an `iife` artifact. If it would be useful, potentially we should have an example for different output formats (e.g. `example-iife`, `example-umd`, etc)

**Comment by distante** [comment]
Hi again!

Nope, it does not resolves the problem because it has a require in there. The iife build should be usable directly in a browser using `<script src=iife.js />`

I use the iife as lib bundle to be imported in non es6 Environments (like IE10)

**Comment by bmuenzenmeyer** [comment]
I couldn't get this working either and just ended up importing the polyfill at the top of my input file

**Comment by JRJurman** [comment]
@bmuenzenmeyer like I said before, do you have an example repo, and what your final build looked like when it did work as expected? I don't actually use  this polyfill in any active project, so if you have an example, that would help me (and others who want to contribute) diagnose what isn't working.

**Comment by JRJurman** [comment]
@bmuenzenmeyer @distante 

I've updated the examples and the interface of the plugin to be more intuitive and match real projects more closely.

Take a look, and tell me if this is closer to what you need, or if it's way off the mark.

**Comment by distante** [comment]
Hi @JRJurman I just moved away to append the [polyfills manually](https://github.com/distante/saninn-logger/blob/master/scripts/prepend-iife-polyfills.js).

But I will try it when I have a new project that needs polyfills.
