### ISSUE TITLE
Polyfills not injected early enough

### ISSUE THREAD

**Issue by antony** [JRJurman/rollup-plugin-polyfill#4]
Thanks for this plugin - it is something I too wanted to implement, and add support for polyfill.io.

I've noticed that this plugin doesn't help when supporting browsers like IE11, since it doesn't appear that polyfills are injected early enough into the bundle. Is this a limitation of rollup?

**Comment by JRJurman** [comment]
Hello @antony do you have an example of what you're trying to polyfill, in a repo or code setup? I'm going to dedicate some time to flesh out the existing example into something that reflects more what a real project looks like, but this might help in case I'm missing a use case 😄

**Comment by antony** [comment]
@JRJurman sure - actually it's another Rich Harris project!

We're trying to find a path to decent, our of the box IE support for Sapper. Currently we have it with this: https://github.com/antony/sapper-ie but the polyfills are annoying and manual. I'd like to inject those polyfills directly into the legacy build https://github.com/antony/sapper-ie/blob/master/rollup.config.js#L44

However, when I use the plugin, it seems that there is a bunch of code before the polyfills that would only run when polyfilled... :)

Hope this is helpful!

**Comment by JRJurman** [comment]
@antony I tried to read your rollup config, but it was slightly difficult to follow... That being said, I've updated the examples and the interface of the plugin to be more intuitive and match real projects more closely.

Take a look, and tell me if this is closer to what you need, or if it's way off the mark.
