### ISSUE TITLE
TypeError: this.getModuleInfo is not a function at Object.transform

### ISSUE THREAD

**Issue by ildar-icoosoft** [JRJurman/rollup-plugin-polyfill#5]
I'm getting `TypeError: this.getModuleInfo is not a function at Object.transform` when I execute `npm start --es5`

my code:
`polyfill(["core-js/es6/promise", "core-js/es6/object", "core-js/es6/function", "core-js/es6/array", "core-js/es7/object"])`

**Comment by JRJurman** [comment]
@ildar-icoosoft Hello! I tried modifying my example using core-js, and it appears that the `/es6` and `/es7` didn't seem to resolve correctly.... Not sure if you have a different version, but this seemed to work for me:

```javascript
const polyfill = require('../src/index')
const resolve = require('rollup-plugin-node-resolve')
const commonjs = require('rollup-plugin-commonjs')

const plugins = [
  resolve(),
  commonjs(),
  // polyfill(['es6-object-assign/auto', './string-reverse.js']),
  polyfill(["core-js/es/promise", "core-js/es/object", "core-js/es/function", "core-js/es/array", "core-js/es/object"])
]

export default {
  input: 'index.js',
  output: {
    file: 'bundle.js',
    format: 'iife',
    name: 'example'
  },
  plugins: plugins
}
```

Can you potentially provide more details / a bare-bones example showing this issue?

**Comment by JRJurman** [comment]
To clarify, even when the paths were `es6` and `es7`, I didn't get the same error you saw, so if you could detail which versions you are using for everything, that might clear up things as well.

**Comment by ildar-icoosoft** [comment]
I get this error in old StencilJs version (0.18.0). I can't replicate this error in latest StencilJs, so I close this issue
