### ISSUE TITLE
Consider changing how polyfills are injected

### ISSUE THREAD

**Issue by lukastaegert** [JRJurman/rollup-plugin-polyfill#8]
Currently, this plugin uses the `isEntry` flag in the transform hook to identify entry points. This is not really reliable, though:
* Via [`this.emitFile`](https://rollupjs.org/guide/en/#thisemitfile), modules can become entry points even after they have been fully transformed. This has already been a problem for a long time. Recently, something more severe was added, though:
* Via [`this.load`](https://rollupjs.org/guide/en/#thisload), plugins can "pre-load" modules even before they are entry points. One technique that completely breaks this plugin is to pre-load a module in the `resolveId` hook before actually resolving it.

To avoid these issues, I would recommend to switch this plugin to a different technique which I also put as an [example in the docs](https://rollupjs.org/guide/en/#resolveid):

```js
function injectPolyfillPlugin() {
  return {
    name: 'inject-polyfill',
    async resolveId(source, importer, options) {
      if (options.isEntry) {
        // We need to skip this plugin to avoid an infinite loop
        const resolution = await this.resolve(source, importer, { skipSelf: true, ...options });
        // If it cannot be resolved or is external, just return it so that
        // Rollup can display an error
        if (!resolution || resolution.external) return resolution;
        // In the load hook of the proxy, we want to use this.load to find out
        // if the entry has a default export. In the load hook, however, we no
        // longer have the full "resolution" object that may contain meta-data
        // from other plugins that is only added on first load. Therefore we
        // trigger loading here without waiting for it.
        this.load(resolution);
        return `${resolution.id}?entry-proxy`;
      }
      return null;
    },
    async load(id) {
      if (id.endsWith('?entry-proxy')) {
        const entryId = id.slice(0, -'?entry-proxy'.length);
        // We need to load and parse the original entry first because we need
        // to know if it has a default export
        const { hasDefaultExport } = await this.load({ id: entryId });
        let code = `import 'polyfill';export * from ${JSON.stringify(entryId)};`;
        // Namespace reexports do not reexport default, so we need special
        // handling here
        if (hasDefaultExport) {
          code += `export { default } from ${JSON.stringify(entryId)};`;
        }
        return code;
      }
      return null;
    }
  };
}
```

Note though that this will be a breaking change for the plugin as it raises the minimum required Rollup version to [2.66.0](https://github.com/rollup/rollup/releases/tag/v2.66.0). Still I would very much recommend that you adopt it, especially since I see this plugin as a valuable contribution to the Rollup ecosystem (I was actually made aware of it when working on rollup/plugins#1038).

**Comment by kzc** [comment]
I followed the cross linked PR comment to this issue:

https://github.com/rollup/plugins/pull/1038#issuecomment-1019527335

> Ok, I think there is actually a "fix" I can add to this PR that will avoid the breaking change for rollup-plugin-polyfill.
> The approach would basically be to proxy ALL entry points. When transforming the proxy, isEntry has the correct value so the plugin would work again.
> However I stumbled across some other things I want to improve in Rollup first, so it might take another few days until I can push this.

Wouldn't it be better to simply not change this plugin at all and wait for the fix in rollup?

I don't think it's reasonable for this or any other plugin to have knowledge of the inner workings of `@rollup/plugin-commonjs` `?entry-proxy` to have a reliable `this.getModuleInfo(id).isEntry` value in the `transform` hook.

**Comment by lukastaegert** [comment]
The plugin can already be broken by using `this.emitFile` in another plugin, and by using `this.load` in certain places. And the only way to avoid this is to change how it works. The "fix" in the commonjs plugin only delays until some other plugin triggers this issue and causes headaches for the people debugging it.

> I don't think it's reasonable for this or any other plugin to have knowledge of the inner workings of @rollup/plugin-commonjs ?entry-proxy to have a reliable this.getModuleInfo(id).isEntry value in the transform hook.

I do not think it is reasonable for any other plugins to have knowledge of the inner workings of rollup-plugin-polyfill. And as I said, it just is not possible to have a reliable value of `isEntry` in the transform hook.

And there is no fix in Rollup that can prevent this except breaking the `this.emitFile` and `this.load` APIs in ways that will cause many more headaches.

**Comment by kzc** [comment]
This is a very simple plugin using just the `transform` hook. It is not unique in that regard. My concern is why any plugin should have to be familiar with the implementation details of `@rollup/plugin-commonjs` just to reliably ascertain whether the hook is dealing with an entry point. I thought plugins ought to operate without knowledge of each other. The proposed fix appears to break that abstraction and principle of isolation. I just can't help but think there exists a simpler solution to this problem. If `isEntry` has never been reliable as a value within `transform` perhaps a similarly named method returning a Promise can be created in `ModuleInfo` that the `transform` method could `await` on.

**Comment by lukastaegert** [comment]
You cannot trust it before the `buildEnd` hook unfortunately, so waiting for it would create a deadlock. So it will always be inherently unreliable in the `transform` hook. The only reliable way to detect entry points is to intercept `resolveId`.

In the next major, we could also set this attribute to `null` before it is reliable, but I am not sure this is a good idea.

**Comment by lukastaegert** [comment]
Simple example plugin that breaks this plugin via `emitFile` and shows, why you cannot wait for `isEntry` it in the transform hook:

```js
function evilPlugin() {
  return {
    transform(code, id) {
      // this turns "foo" into an entry point
      if (id === 'foo') this.emitFile({type: 'chunk', id: 'foo'});
    }
  }
}
```

If you place this plugin after rollup-plugin-polyfill, "foo" will not be recognized as an entry point even though it is. And I do not see why it should be forbidden to write that plugin. It could be useful to turn files into entry points based on their content.

If you do it in `moduleParsed`, order even becomes irrelevant:

```js
function evilPlugin() {
  return {
    moduleParsed({id}) {
      // this turns "foo" into an entry point
      if (id === 'foo') this.emitFile({type: 'chunk', id: 'foo'});
    }
  }
}
```

**Comment by kzc** [comment]
If knowledge of the implementation details of `@rollup/plugin-commonjs` is necessary for the correct functioning of any plugin then it might as well be rolled into rollup core. If plugin specific details like `?entry-proxy` cannot be hidden from plugin authors, can the boilerplate in the `resolveId` and `load` methods in the proposed workaround at the top of this ticket be put behind a pair of simple facade calls that would normally be no-ops unless `@rollup/plugin-commonjs` is used in which case it would register the necessary entry point determination logic?

**Comment by lukastaegert** [comment]
You DO understand this is not a problem of `@rollup/plugin-commonjs` but a general problem of Rollup's API and the ability to write arbitrary plugins? As I already said, I will rewrite it in a way so that it will not cause additional problems. But OTHER plugins can still break this plugin because `ModuleInfo.isEntry` just cannot be made reliable in the `transform` hook. I can give you more ad-hoc examples of potentially useful things that plugins can do that would break this plugin. So if you do NOT want plugins to have to know about other plugins, THIS plugin needs to change because it works on unsafe assumptions.

But we could indeed make the code nicer by encoding the presence of the default export into the proxy, something like

```js
function injectPolyfillPlugin() {
  return {
    name: 'inject-polyfill',
    async resolveId(source, importer, options) {
      if (options.isEntry) {
        const resolution = await this.resolve(source, importer, { skipSelf: true, ...options });
        if (!resolution || resolution.external) return resolution;
        const { hasDefaultExport } = await this.load(resolution);
        return `${resolution.id}?entry-proxy${hasDefaultExport ? '-with-default' : ''}`;
      }
      return null;
    },
    load(id) {
      const [entryId, postfix] = id.split('?');
      if (postfix.startsWith('entry-proxy') {
        let code = `import 'polyfill';export * from ${JSON.stringify(entryId)};`;
        if (postfix === 'entry-proxy-with-default') code += `export { default } from ${JSON.stringify(entryId)};`
        return code;
      }
      return null;
    }
  };
}
```

**Comment by kzc** [comment]
I do (and did) understand what's going on regarding isEntry and transform. In my previous comment I was offering a suggestion to hide the implementation details of `@rollup/plugin-commonjs` from this and other plugins to improve the rollup API experience. Oh well, we're not going to agree on this matter.

**Comment by JRJurman** [comment]
It has been a long time since I've worked on this repo, and even then I didn't have a strong idea of what I was doing. I'm happy to entertain any PR, and we can continue the conversation there. I'm happy to introduce what might be a breaking change with a new major version bump (that's what those numbers are for 😄).

**Comment by lukastaegert** [comment]
I will see if I can prepare a proper PR soon.

@kzc

> In my previous comment I was offering a suggestion to hide the implementation details of @rollup/plugin-commonjs

This is the part that really makes me wonder what implementation details you are referring to. I can really only assume that you are referring to this comment https://github.com/rollup/plugins/pull/1038#issuecomment-1017666507 where it sounds this change is critical to make the commonjs plugin work.

> If plugin specific details like ?entry-proxy

`?entry-proxy` is a completely arbitrary string that has nothing to do with the commonjs plugin, and probably even a bad one. The example should probably use something that is less likely to collide with other plugins like `?polyfill-entry`.

But as I already stated in the next comment below, I have a way of changing the commonjs PR so that it is not necessary to change the polyfill plugin at all to accommodate the commonjs plugin.

So the remaining criticism I see from you is that a "proper" solution is just more complicated, or that it is not immediately clear why the current solution is not safe. I will try to improve documentation to make clear why isEntry is not reliable. But I do not see how I could make it any simpler except by introducing even more API surface, which seems overkill for me (and I would not even know what APIs those should be).

**Comment by kzc** [comment]
> `?entry-proxy` is a completely arbitrary string that has nothing to do with the commonjs plugin

@lukastaegert You are quite right. I was mistaken. The entire premise of my critique was based on a faulty assumption. I had `commonjs` plugin on the brain and confused it with `?commonjs-proxy`. Sorry about that. I imagine you were as perplexed with my comments as I was with yours. :-)
